FROM node:22-alpine AS base

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
RUN apk add --no-cache libc6-compat

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci --omit=optional --no-audit --no-fund && npm cache clean --force

FROM base AS builder
ARG BUILD_MAX_OLD_SPACE_SIZE=1024
ARG NEXT_PUBLIC_SITE_URL=https://tecnolts.com
ARG NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=
ARG NEXT_PUBLIC_YANDEX_VERIFICATION=
ARG NEXT_PUBLIC_YAHOO_VERIFICATION=
ARG NEXT_PUBLIC_CONTACT_EMAIL=
ARG NEXT_PUBLIC_CONTACT_PHONE=
ARG NEXT_PUBLIC_WHATSAPP_PHONE=
ARG NEXT_PUBLIC_WHATSAPP_MESSAGE=
ARG NEXT_PUBLIC_CONTACT_LOCALITY=
ARG NEXT_PUBLIC_CONTACT_REGION=
ARG NEXT_PUBLIC_CONTACT_COUNTRY_CODE=
ARG NEXT_PUBLIC_CONTACT_COUNTRY_NAME=
ARG NEXT_PUBLIC_CONTACT_STREET_ADDRESS=
ARG NEXT_PUBLIC_CONTACT_POSTAL_CODE=
ARG NEXT_PUBLIC_CONTACT_LATITUDE=
ARG NEXT_PUBLIC_CONTACT_LONGITUDE=
ARG NEXT_PUBLIC_GOOGLE_MAPS_URL=
ARG NEXT_PUBLIC_GOOGLE_BUSINESS_PROFILE_URL=
ARG NEXT_PUBLIC_LINKEDIN_URL=
ARG NEXT_PUBLIC_FACEBOOK_URL=
ARG NEXT_PUBLIC_INSTAGRAM_URL=
ARG NEXT_PUBLIC_X_URL=
ARG NEXT_PUBLIC_TIKTOK_URL=
ARG NEXT_PUBLIC_YOUTUBE_URL=
ENV NODE_OPTIONS=--max-old-space-size=${BUILD_MAX_OLD_SPACE_SIZE}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=${NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION}
ENV NEXT_PUBLIC_YANDEX_VERIFICATION=${NEXT_PUBLIC_YANDEX_VERIFICATION}
ENV NEXT_PUBLIC_YAHOO_VERIFICATION=${NEXT_PUBLIC_YAHOO_VERIFICATION}
ENV NEXT_PUBLIC_CONTACT_EMAIL=${NEXT_PUBLIC_CONTACT_EMAIL}
ENV NEXT_PUBLIC_CONTACT_PHONE=${NEXT_PUBLIC_CONTACT_PHONE}
ENV NEXT_PUBLIC_WHATSAPP_PHONE=${NEXT_PUBLIC_WHATSAPP_PHONE}
ENV NEXT_PUBLIC_WHATSAPP_MESSAGE=${NEXT_PUBLIC_WHATSAPP_MESSAGE}
ENV NEXT_PUBLIC_CONTACT_LOCALITY=${NEXT_PUBLIC_CONTACT_LOCALITY}
ENV NEXT_PUBLIC_CONTACT_REGION=${NEXT_PUBLIC_CONTACT_REGION}
ENV NEXT_PUBLIC_CONTACT_COUNTRY_CODE=${NEXT_PUBLIC_CONTACT_COUNTRY_CODE}
ENV NEXT_PUBLIC_CONTACT_COUNTRY_NAME=${NEXT_PUBLIC_CONTACT_COUNTRY_NAME}
ENV NEXT_PUBLIC_CONTACT_STREET_ADDRESS=${NEXT_PUBLIC_CONTACT_STREET_ADDRESS}
ENV NEXT_PUBLIC_CONTACT_POSTAL_CODE=${NEXT_PUBLIC_CONTACT_POSTAL_CODE}
ENV NEXT_PUBLIC_CONTACT_LATITUDE=${NEXT_PUBLIC_CONTACT_LATITUDE}
ENV NEXT_PUBLIC_CONTACT_LONGITUDE=${NEXT_PUBLIC_CONTACT_LONGITUDE}
ENV NEXT_PUBLIC_GOOGLE_MAPS_URL=${NEXT_PUBLIC_GOOGLE_MAPS_URL}
ENV NEXT_PUBLIC_GOOGLE_BUSINESS_PROFILE_URL=${NEXT_PUBLIC_GOOGLE_BUSINESS_PROFILE_URL}
ENV NEXT_PUBLIC_LINKEDIN_URL=${NEXT_PUBLIC_LINKEDIN_URL}
ENV NEXT_PUBLIC_FACEBOOK_URL=${NEXT_PUBLIC_FACEBOOK_URL}
ENV NEXT_PUBLIC_INSTAGRAM_URL=${NEXT_PUBLIC_INSTAGRAM_URL}
ENV NEXT_PUBLIC_X_URL=${NEXT_PUBLIC_X_URL}
ENV NEXT_PUBLIC_TIKTOK_URL=${NEXT_PUBLIC_TIKTOK_URL}
ENV NEXT_PUBLIC_YOUTUBE_URL=${NEXT_PUBLIC_YOUTUBE_URL}
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV APP_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup -S nodejs && adduser -S nextjs -G nodejs

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

CMD ["node", "server.js"]

FROM base AS dev
ENV NODE_ENV=development
ENV APP_ENV=development
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
