version: '3.8'

services:
  web:
    profiles: ["production"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-production}
    container_name: tecnolts-app
    hostname: tecnolts-app
    restart: unless-stopped
    environment:
      NODE_ENV: ${APP_ENV:-production}
      APP_ENV: ${APP_ENV:-production}
      PORT: ${PORT:-3000}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      EMAIL_TO: ${EMAIL_TO}
    working_dir: /app
    command: npm run start -- --hostname 0.0.0.0 --port ${PORT:-3000}
    ports:
      - "${PORT:-3008}:${PORT:-3000}"
    networks:
      edge:
        aliases:
          - tecnolts-app

  web-dev:
    profiles: ["development"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-development}
    container_name: tecnolts-app-dev
    hostname: tecnolts-app-dev
    restart: unless-stopped
    environment:
      NODE_ENV: ${APP_ENV:-development}
      APP_ENV: ${APP_ENV:-development}
      PORT: ${PORT:-3000}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      EMAIL_TO: ${EMAIL_TO}
    working_dir: /app
    command: npm run dev -- --hostname 0.0.0.0 --port ${PORT:-3000}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT:-3008}:${PORT:-3000}"
    networks:
      edge:
        aliases:
          - tecnolts-app

networks:
  edge:
    external: true
    name: edge
